#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S3,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int count = 0;

	/*while(true){
			displayBigTextLine(4, "Reflected:  %d", SensorValue[Colour]);
			sleep(20);
	}*/
	
	while (SensorValue(touchSensor) != 0) {
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		displayCenteredBigTextLine(4, "Counter: %d", count);
		if (SensorValue(Colour) < 40) {
			
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			sleep(500);
			setMotorSpeed(leftMotor, 10);
			setMotorSpeed(rightMotor, 10);
			sleep(1000);
			count++;
		}

	}
}