#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S3,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	
	displayTextLine(1, "Start");
	wait1Msec(1000);
	eraseDisplay();
	
	//while on dark line move Robot straight
	while(SensorValue[Colour] == 25) //SensorValue[Colour] == 25    
	{
		displayTextLine(3, "Dark");
		setMotorSpeed(leftMotor, 30);
		setMotorSpeed(rightMotor, 30);
		
	}
	
}