#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     touchSensor2,   sensorEV3_Touch, modeEV3Bump)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void moving();
void changeLocation();
void ultrason();
void ultrasonMoving();
void reset();
task main()
{
	moving();
	changeLocation();
	ultrason();
	changeLocation();
	ultrasonMoving();
	changeLocation();
	
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 720, 50);
	sleep(3000);
}
void moving() {
	SensorType[S1] = sensorEV3_Touch;
	SensorType[S3] = sensorEV3_Touch;
	while(SensorValue(touchSensor) == 0 && SensorValue(touchSensor2) == 0) {
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}
}
void ultrason() {
	SensorType[S4] = sensorEV3_Ultrasonic;
	while(SensorValue(sonarSensor) > 25) {
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);      
	}
}
void ultrasonMoving() {
	SensorType[S1] = sensorEV3_Touch;
	SensorType[S3] = sensorEV3_Touch;
	SensorType[S4] = sensorEV3_Ultrasonic;
	while(SensorValue(touchSensor) == 0 && SensorValue(touchSensor2) == 0 && SensorValue(sonarSensor) > 25) {
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}
}
void changeLocation() {
		reset();
		setMotorSpeed(leftMotor, -25);
		setMotorSpeed(rightMotor, -25);
		sleep(1500);
		
		
		setMotorSyncEncoder(leftMotor, rightMotor, -50, 370, 50);
		sleep(2000);
}
void reset() {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
}