#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          lefftMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task test();

task main()
{
	
	startTask(test);
	
	eraseDisplay(); // Clear the display
	displayCenteredTextLine(2,"gyro resetting");
	
	SensorType[S2] = sensorEV3_Gyro; // set sensor to port 2 
	sleep(400);
	resetGyro(S2);
	sleep(400);
	                            
	
	while(true)
	{
		
		setMotorTarget(armMotor, -50, 10);
		waitUntilMotorStop(armMotor);
		setMotorTarget(armMotor, 50, 10);
		waitUntilMotorStop(armMotor);
		
		
	
  }//end while loop 
  
  
}//end main()

task test()
{
	while(1)
	{
		int gyroRate = 0;
	
		displayBigTextLine(6, "%d", getGyroDegrees(gyroSensor));
		
			// Read the current rate value in degrees/second
		gyroRate = getGyroDegrees(S2);                   
		
		//displayBigTextLine(2,"Heading= %d",gyroRate);
		
		/*
		// Clip the value of the gyro to -50 to +50 (min and max motor speeds)
		if(gyroRate > 50)
		{
		}
		else if (gyroRate > 50)
			gyroRate = 100;
		else if (gyroRate < -1)
			gyroRate = 50;
   	else if (gyroRate < -45)
			gyroRate = 0;
		*/	
			
		//speeds to the rate of the gyro
		setMotorSync(motorB, motorC, 0, gyroRate * 2);

		sleep(10);
		
	  
		
	}
}