#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	
	int Angle;
	
	eraseDisplay();  // Clear the display
	displayCenteredTextLine(4,"gyro resetting");
	
	SensorType[S2] = sensorEV3_Gyro; // set sensor to port 4
	
	sleep(1000);
	resetGyro(S2);
	sleep(2000);
	displayCenteredTextLine(4,"Angle =%d",getGyroDegrees(S4));
	sleep(2000);
	
	
	// Turn Robot 360 degrees around, then stop:
	Angle=getGyroDegrees(S2); // Get the starting angle which should be 0
	displayCenteredTextLine(4,"Angle =%d",Angle);
	
	setMotorSync(motorB, motorC, -100, 10); // -100 is forward on first motor and reverse on second one
	displayCenteredTextLine(4,"rotating 360");
	while (abs(Angle) < 360)
	{
		sleep(2);
		Angle=getGyroDegrees(S2);
		displayCenteredBigTextLine(5,"current angle %4d",Angle);
	}
	
	playTone(440,10);
	setMotorSync(motorB, motorC, 0, 0); // stop the motors
	
	sleep(2000);
	
}